### ISSUE TITLE
dynamic linking

### ISSUE THREAD

**Issue by JernejL** [plashenkov/SQLite3-Delphi-FPC#2]
I am working on a modification to allow for dynamic loading of the library, would you accept this as a patch?

**Comment by plashenkov** [comment]
Hi JernejL! Just send a pull request, I'll look into it for sure! :)

P.S. The lib is already linked dynamically. Or what do you mean?

**Comment by JernejL** [comment]
What i mean is dynamic loading it as well, so using loadlibrary & getprocaddress

**Comment by plashenkov** [comment]
Let's close this.
